{
 "title": "Patient | Data scientist layout",
 "description": "Patient view",
 "time": { "from": "2012-08-04T16:10:10.625Z", "to": "2012-08-04T16:21:19.775Z" },
 "templating": {
  "list": [
   {
    "name": "patient",
    "label": "Patient",
    "query": "SHOW TAG VALUES WITH KEY=\"patient\""
   },
   { "name": "feature_1", "label": "Main feature", "query": "SHOW FIELD KEYS FROM features" },
   { "name": "feature_2", "label": "Secondary feature", "query": "SHOW FIELD KEYS FROM features" }
  ]
 },
 "panels": [
  {
   "title": "$feature_1",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$feature_1",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "patient" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "features",
     "query": "SELECT mean(/^$feature_1$/) FROM \"autogen\".\"features\" WHERE (\"patient\" =~ /^$patient$/) AND $timeFilter GROUP BY time(1s), \"patient\" fill(linear)",
     "select": [
      [
       { "params": [ "/^$feature_1$/" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "patient", "operator": "=~", "value": "/^$patient$/" }
     ]
    }
   ]
  },
  {
   "title": "Statistics",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT metric, value FROM session_metrics \nWHERE value != value + 1\nAND CONCAT(REPEAT('0', 8 - length(patient_id::varchar(255))), patient_id, '_', session_id) = '$patient'\n"
    }
   ]
  },
  {
   "title": "Shap waterfall plot",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT * FROM \"autogen\".\"features\" WHERE (\"patient\" =~ /^$patient$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "rawSql": "SELECT value FROM metrics WHERE metric = 'shap_expected_value'"
    }
   ]
  },
  {
   "title": "Correlation between $feature_1 and $feature_2",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 7 },
   "targets": [
    {
     "measurement": "features",
     "query": "SELECT /^$feature_1$/, /^$feature_2$/ FROM \"autogen\".\"features\" WHERE (\"patient\" =~ /^$patient$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "/^$feature_2$/" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "patient", "operator": "=~", "value": "/^$patient$/" }
     ]
    }
   ]
  },
  {
   "title": "Shap summary plot",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "measurement": "features",
     "query": "SELECT * FROM \"autogen\".\"features\" WHERE (\"patient\" =~ /^$patient$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "patient", "operator": "=~", "value": "/^$patient$/" },
      { "condition": "AND", "key": "patient", "operator": "=", "value": "select tag value" }
     ]
    }
   ]
  }
 ]
}