{
 "title": "Patient | Doctor layout",
 "description": "Patient view",
 "time": { "from": "2012-08-04T16:10:10.625Z", "to": "2012-08-04T16:21:19.775Z" },
 "templating": {
  "list": [
   {
    "name": "patient",
    "label": "Patient",
    "query": "SHOW TAG VALUES WITH KEY=\"patient\""
   },
   { "name": "features", "query": "SHOW FIELD KEYS FROM features" }
  ]
 },
 "panels": [
  {
   "title": "Electrocardiogram",
   "type": "graph",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "ECG ($tag_patient)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "channel" ], "type": "tag" },
      { "params": [ "patient" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ecg",
     "select": [
      [
       { "params": [ "Tension (uV)" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "patient", "operator": "=~", "value": "/^$patient$/" }
     ]
    }
   ]
  },
  {
   "title": "Patient",
   "type": "aidanmountford-html-panel",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "format": "short",
   "targets": [
    {}
   ]
  },
  {
   "title": "$features",
   "type": "graph",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "patient" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "features",
     "query": "SELECT ${features:raw} FROM \"autogen\".\"features\" WHERE (\"patient\" =~ /^$patient$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "${features:raw}" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "patient", "operator": "=~", "value": "/^$patient$/" }
     ]
    }
   ]
  },
  {
   "title": "Lime feature importance",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT * FROM \"autogen\".\"features\" WHERE (\"patient\" =~ /^$patient$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}