version: '3.3'

services:
  influxdb:
    image: influxdb:1.8
    container_name: aura-influxdb
    ports:
      - '${INFLUXDB_PORT}:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=${INFLUXDB_DATABASE}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}

  postgres:
    image: postgres:11
    container_name: aura-postgresql
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres-storage:/var/lib/postgresql/data
      - ./scripts/create_multiple_databases.sh:/docker-entrypoint-initdb.d/create_multiple_databases.sh
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_MULTIPLE_DATABASES: ${POSTGRES_DATABASE_GRAFANA}
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}" ]
      interval: 5s
      retries: 5
    restart: always

  grafana:
    image: grafana/grafana:7.3.4
    container_name: aura-grafana
    restart: on-failure
    ports:
      - '${GRAFANA_PORT}:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./conf/provisioning:/etc/grafana/provisioning
      - ./conf/grafana.ini:/etc/grafana/grafana.ini
    depends_on:
      - influxdb
      - postgres
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_DATABASE_TYPE=postgres
      - GF_DATABASE_HOST=postgres:5432
      - GF_DATABASE_NAME=${POSTGRES_DATABASE_GRAFANA}
      - GF_DATABASE_USER=${POSTGRES_USER}
      - GF_DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - GF_INSTALL_PLUGINS=ae3e-plotly-panel,aidanmountford-html-panel # v0.4.0
      - INFLUXDB_DATABASE=${INFLUXDB_DATABASE}
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}

volumes:
  influxdb-storage:
  grafana-storage:
  postgres-storage:
